### ISSUE TITLE
v0.7.46 err

### ISSUE THREAD

**Issue by xtxf0009** [nhaouari/obsidian-textgenerator-plugin#346]
![image](https://github.com/user-attachments/assets/0310cd3e-d10a-4b63-a147-a7cf171568b3)
TG Error: (void 0) is not a function

**Comment by xiyeming** [comment]
俺也一样，降回 0.7.43 版本了。

**Comment by scstc** [comment]
我也是一样

**Comment by jamesKhor** [comment]
> [!failure]- Failure 
>   TypeError: n.text is not a function
>   
>   - plugin:obsidian-textgenerator-plugin:1900 t.request
>     plugin:obsidian-textgenerator-plugin:1900:569
>   
>   - plugin:obsidian-textgenerator-plugin:1905 async eval
>     plugin:obsidian-textgenerator-plugin:1905:422
>   
>

**Comment by acrobatman** [comment]
> ![image](https://private-user-images.githubusercontent.com/58800553/400609134-039c8257-3161-4641-886f-4dadf73c5419.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNTU1OTksIm5iZiI6MTczNjI1NTI5OSwicGF0aCI6Ii81ODgwMDU1My80MDA2MDkxMzQtMDM5YzgyNTctMzE2MS00NjQxLTg4NmYtNGRhZGY3M2M1NDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDEzMDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0YzY3YThjZjdiNWE2MTA4YTc1OTI2ZTIxZTA3MWY4MTBjZDRmNTVjM2E1ZjAyYWQ3NzY5NWM1NjNlMjYyOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EgDKMAr65nhDZEzB2heaHT68AMy0hL3Ci96L3qFqhh0)
> 
> ```
>  Failure 
> >   TypeError: n.text is not a function
> >   
> >   - plugin:obsidian-textgenerator-plugin:1900 t.request
> >     plugin:obsidian-textgenerator-plugin:1900:569
> >   
> >   - plugin:obsidian-textgenerator-plugin:1905 async eval
> >     plugin:obsidian-textgenerator-plugin:1905:422
> >   
> >  
> ```
> 
> tried to use custom model, deepseek api but failed

DeepSeek is ok, I have already used it.
What's the your deepseek configuration？

**Comment by jamesKhor** [comment]
> > ![image](https://private-user-images.githubusercontent.com/58800553/400609134-039c8257-3161-4641-886f-4dadf73c5419.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNTU1OTksIm5iZiI6MTczNjI1NTI5OSwicGF0aCI6Ii81ODgwMDU1My80MDA2MDkxMzQtMDM5YzgyNTctMzE2MS00NjQxLTg4NmYtNGRhZGY3M2M1NDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDEzMDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0YzY3YThjZjdiNWE2MTA4YTc1OTI2ZTIxZTA3MWY4MTBjZDRmNTVjM2E1ZjAyYWQ3NzY5NWM1NjNlMjYyOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EgDKMAr65nhDZEzB2heaHT68AMy0hL3Ci96L3qFqhh0)
> > ```
> >  Failure 
> > >   TypeError: n.text is not a function
> > >   
> > >   - plugin:obsidian-textgenerator-plugin:1900 t.request
> > >     plugin:obsidian-textgenerator-plugin:1900:569
> > >   
> > >   - plugin:obsidian-textgenerator-plugin:1905 async eval
> > >     plugin:obsidian-textgenerator-plugin:1905:422
> > >   
> > >  
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > tried to use custom model, deepseek api but failed
> 
> DeepSeek is ok, I have already used it. What's the your deepseek configuration？

Im running okay now. I was using the `https://api.deepseek.com/chat/` as api endpoint. changing api endpoint to `https://api.deepseek.com/chat/completions` makes it run perfectly.

**Comment by maksim77** [comment]
```
plugin:obsidian-textgenerator-plugin:2123 TypeError: (void 0) is not a function
    at OII (plugin:obsidian-textgenerator-plugin:1829:5990)
    at new WM (plugin:obsidian-textgenerator-plugin:1829:6446)
    at aX (plugin:obsidian-textgenerator-plugin:1830:60)
    at c.request (plugin:obsidian-textgenerator-plugin:1903:70)
    at async eval (plugin:obsidian-textgenerator-plugin:1905:422)
```

tg version: v0.7.46
Obsidian version: 1.8.1

**Comment by haouarihk** [comment]
i need more information. or a reproduceable template.
when does it appear, only in mobile?
which profile is used and if custom configuration is being used.

**Comment by maksim77** [comment]
This settins work fine on 0.7.43 but produce `(void 0) is not a frunction` on last build
```json
    "Default (Custom) 3": {
      "endpoint": "https://api.aitunnel.ru/v1/chat/completions",
      "custom_header": "{\n    \"Content-Type\": \"application/json\",\n    authorization: \"Bearer {{api_key}}\"\n}",
      "custom_body": "{\n    model: \"{{model}}\",\n    temperature: {{temperature}},\n    top_p: {{top_p}},\n    frequency_penalty: {{frequency_penalty}},\n    presence_penalty: {{presence_penalty}},\n    max_tokens: {{max_tokens}},\n    n: {{n}},\n    stream: {{stream}},\n    stop: \"{{stop}}\",\n    messages: {{stringify messages}}\n}",
      "model": "gpt-4o-mini",
      "sanatization_streaming": "// catch error\nif (res.status >= 300) {\n  const err = data?.error?.message || JSON.stringify(data);\n  throw err;\n}\nlet resultText = \"\";\nconst lines = chunk.split(\"\ndata: \");\n\nconst parsedLines = lines\n    .map((line) => line.replace(/^data: /, \"\").trim()) // Remove the \"data: \" prefix\n    .filter((line) => line !== \"\" && line !== \"[DONE]\") // Remove empty lines and \"[DONE]\"\n    .map((line) => {\n        try {\n            return JSON.parse(line)\n        } catch { }\n    }) // Parse the JSON string\n    .filter(Boolean);\n\nfor (const parsedLine of parsedLines) {\n    const { choices } = parsedLine;\n    const { delta } = choices[0];\n    const { content } = delta;\n    // Update the UI with the new content\n    if (content) {\n        resultText += content;\n    }\n}\nreturn resultText;",
      "sanatization_response": "// catch error\nif (res.status >= 300) {\n  const err = data?.error?.message || JSON.stringify(data);\n  throw err;\n}\n\n// get choices\nconst choices = data.choices.map(c=> c.message);\nconsole.log(choices);\n// the return object should be in the format of \n// { content: string }[] \n// if there's only one response, put it in the array of choices.\nreturn choices;",
      "frequency_penalty": 0,
      "presence_penalty": 0.5,
      "top_p": 1,
      "api_key": "",
      "CORSBypass": true
    }
  },
  ```

**Comment by haouarihk** [comment]
this should be fixed in version 0.7.47
